# Generated by Django 3.2.4 on 2021-06-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('autor', models.CharField(max_length=70)),
                ('album', models.CharField(max_length=70)),
                ('duracion', models.CharField(max_length=20)),
                ('fechaLanzamiento', models.DateField()),
            ],
        ),
    ]
