# Generated by Django 3.2.4 on 2021-06-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_fechalanzamiento_cancion_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancion',
            old_name='fecha',
            new_name='fechaLanzamiento',
        ),
    ]
